### PR TITLE
Feature repare open shell vis

### LINKED ISSUE #143: open shell cube 3D visualizations + adding of test cases
When running an open shell cube type calculation two files called jvecalpha.txt and jvecbeta.txt are generated together with jvec.txt. We visualize jvec.txt as jvec.vti but we do not do this for jvecalpha.txt 
and jvecbeta.txt. The question is should we do this? Is it needed for further studies? I will investigate but in case someone has an idea please share your opinion.

### PR DESCRIPTION
**Pull request by heikef**
closes #143 
1. reintroduced visualization but now based on vti files instead of cube files
2. information stored before on file.cube and file_quasi.cube put on one vti file
3. added tests for 3D + integration for square C4H4 in the lowest triplet state but using DFT (B3LYP/def2TZVP) instead of CCSD as done in Ref. J. Chem. Phys. 134, 054123 (2011). 
4. tested against results obtained with branch "stable" assuming that this is correct (further tests might be a good idea though) 
5. merging would be good to have a working develop branch that is capable to treat open shell systems as well.

### CODE REVIEW

**Comment by bast** [comment]
Please browse the diff: https://github.com/qmcurrents/gimic/pull/147/files
It contains changes done by me. Something did not go well.

**Comment by bast** [comment]
Create a backup branch, then update your forked master, then rebase this branch on top of master and then let's look at it again.

**Comment by heikef** [comment]
I updated my branch on the fork with qmcurrents/gimic master, perhaps this caused the problem? Ok, I see if I manage to do what you suggest.

**Comment by heikef** [comment]
I upadted my fork master, then I checked out the working branch and updated the working branch with my updated fork master. The result is "Already up-to-date". It is not clear to me what to rebase now.

**Comment by bast** [comment]
What do you mean by "updated the working branch with my updated fork master"?

**Comment by heikef** [comment]
The changed files seem to appear correctly now. I forgot to push first the updated master. Then the pull on the master from my working branch was ok. The history seems fine but somehow I can not modify the two merge messages into one without messing the history again up.

**Comment by bast** [comment]
And now we need to get rid of the merge commits: https://github.com/qmcurrents/gimic/pull/147/commits

**Comment by heikef** [comment]
I know but this is not working. When I try a rebase I do not get the automatically generated merge commit message in the editor. Do you have an idea on how to fix this? When I do not see all commit messages in the editor I can not squash them.

**Comment by bast** [comment]
What is not working? Have you rebased the branch?

**Comment by heikef** [comment]
I am on my working branch. I try to do git rebase --interactive HEAD~3 this leads to an editor where I can not squash what I want to squash. I would expect the last three recent commits to be visible but this is not the case. The two most recent commits do not appear. What do you mean with "rebase the branch"?

**Comment by bast** [comment]
```
$ git rebase master
```

**Comment by heikef** [comment]
Thanks. This seems to work now, but I do not understand why. What happened when doing git rebase master? Why is doing a git pull on master from my working branch not enough? The automatic merge message disappeared, which is nice.

**Comment by bast** [comment]
Git pull = git fetch + git merge. Git merge is not the same thing as git rebase.

**Comment by heikef** [comment]
git rebase is like squeezing the history of my branch into master and let it look as one history line but here this should not be needed if I would have updated the master branch correctly and not my working branch with the gimic master. 
In case this is useful for the future:
https://stackoverflow.com/questions/2715085/rebasing-and-what-does-one-mean-by-rebasing-pushed-commits#28257263

**Comment by bast** [comment]
No it's not :-) git rebase is like cutting off a branch in a tree and planting it on a different place in the tree.

**Comment by heikef** [comment]
I do not see how you can completely cut it out and plant it somewhere else, but probably this works. At the moment I am fed up with the whole git thing. -)) Either gimic is not working or I am having trouble with git. I wait for the day where both things are not working... The day I start understanding the concept of git I will probably have to switch to svn and then the whole mess starts over again....

**Comment by bast** [comment]
And now we need to reduce 3 commits to 2. I can also squash them here if you prefer. It will *really* pay off to study merging and rebasing a bit to completely understand how they differ.

**Comment by heikef** [comment]
Nope, I messed it up - I will fix it, but thanks for the offer - it is very much appreciated. -)) 
Why making 2 commits out of 3? The messages are meaningful in my opinion. What do you suggest?

**Comment by bast** [comment]
Aha, I did not see that 3. commit is something else than a merge. Ideally a pull request should never contain merge commits. So I think the 3. commit message is simply misleading since it does not contain a merge. This is not a merge commit: https://github.com/qmcurrents/gimic/pull/147/commits/31fc6c6f24dd38a63be0ac83f00c2a6202ba6137

And yeah, this is as painful for me as it is for you but we do it for the great good.

**Comment by heikef** [comment]
Ok. Now we have 2 commit messages. I hope nothing is misleading any more. Thanks for your patience!

**Comment by bast** [comment]
Excellent - thank you for this work and patience!

**Pull request merged**
