### PR TITLE
Clean-up while working on MPI

### PR DESCRIPTION
**Pull request by bast**
This is work in progress - do not merge yet. This is just so that I get it tested, so that you can track progress, and that so that I can get possibly feedback/suggestions.

### CODE REVIEW

**Comment by heikef** [comment]
OK. So far I see no problem with deleted code. It looks you basically added some more if statements.

**Comment by bast** [comment]
Yes, so far just moving if statements to localize the crashes.

**Comment by bast** [comment]
So after a day of poking in the code I am at a point where we need to plan next steps:
- The code is reading input from stdin but it is not trivial to channel stdin to all workers
- I have tried that only one tasks reads and then settings are distributed but this is hard because of complex data structures which are hard to synchronize

In the long term the data structures need to be simplified.

What could work in the short term is that the input file is not read from stdin but given as a positional argument. This is an easy change but will break all current run scripts :-)

Preferences?

**Comment by bast** [comment]
It's better if we discuss this in the issue, not here - I will move the above question to the issue.

**Comment by heikef** [comment]
Good, let's move to the issue then.

**Comment by bast** [comment]
I will remove here the dead ends and keep what is good and let you know once it's ready for review.

**Comment by heikef** [comment]
OK. Thanks for your work.

**Comment by bast** [comment]
Ready for review. I kept only the cleanup part and the launcher part which can be useful for debugging.

**Comment by heikef** [comment]
Are three commits with "rm dead code" really necessary for the history?

**Comment by bast** [comment]
I will squash them into one.

**Comment by heikef** [comment]
All the remaining changes look fine. Thanks for the discussion. We found some good agreements.

**Comment by bast** [comment]
Cool. If you agree with them, please merge. I will continue work in a new PR.

**Comment by heikef** [comment]
Well, I had to wait for all tests to pass before merging.

**Pull request merged**
