### PR TITLE
added the benzene test example into examples with reference files

### PR DESCRIPTION
**Pull request by heikef**
This is related to issue #51 and based on the input files and date we have in /test

### CODE REVIEW

**Comment by bast** [comment]
Super. Only modification I would like you to make is to modify the commit message to auto-close issue #51.

**Comment by heikef** [comment]
OK - next time I will add auto-close and then the number of the issue. Thanks for the hint!

**Comment by bast** [comment]
OK but please try to fix this one (for the exercise).

**Comment by bast** [comment]
```
# edit last commit message
git commit --amend

# never ever push --force to the central repo, only to your fork and only the feature branch
git push --force origin mybranch
```

**Comment by heikef** [comment]
Thank you. I followed your instructions. Please check if this is now acceptable.

**Comment by bast** [comment]
Please follow https://help.github.com/articles/closing-issues-via-commit-messages/.

**Comment by bast** [comment]
Use "closes" or "fixes".

**Comment by heikef** [comment]
Thank you for the link! I understand. One needs to use the right keyword. I think it should work now.

**Comment by bast** [comment]
Sorry for being pedantic but leave out the "issue" ("fixes #N" is enough). Also this should be part of the first commit line so that it is visible in web overviews.

**Comment by heikef** [comment]
Ok - I modified the commit message. It starts now with "closes #51". There is not much left what could be wrong this time. Thanks for being patient!

**Comment by bast** [comment]
And now the finale: please both the message and the closes on one line. And the line should not be longer than approx 50 characters. Be brief and clear. If more info is needed, add a paragraph below.

**Comment by bast** [comment]
This is the reason: https://github.com/qmcurrents/gimic/commits/master - I need to see what is going on without needing to click around and inspect diffs.

**Comment by bast** [comment]
:+1:

**Pull request merged**
