### PR TITLE
remove expensive orbital trafos from dryrun

### PR DESCRIPTION
**Pull request by lnw**

### CODE REVIEW

**Comment by heikef** [comment]
Looks ok to me. Thank you. Could you please add to the commit message that this closes issue #193 ? That is important for the bookkeeping.

**Comment by bast** [comment]
Also from me an upvote. This can also be added to the PR title.

**Comment by bast** [comment]
Also thanks for the typo-fixes.

**Comment by lnw** [comment]
How do I amend the commit message without creating a new commit/pull request?

**Comment by heikef** [comment]
git commit --amend "text" and git push again should work

**Comment by bast** [comment]
Except that you have to then force push. Now we have 3 commits which should be squashed. Either on your side or here via GitHub.

**Comment by heikef** [comment]
git push -f will force the push

**Comment by heikef** [comment]
OK. Thanks for the work, Lukas. I think we can merge it now.

**Pull request merged**
