### PR TITLE
removed not used subroutines 

### PR DESCRIPTION
**Pull request by heikef**
Removed subroutines such as contract2, ctensor2, jtensor2, divergence2 because they are not used. All test went through. I think when these routines are not used we do not need to keep them.

### CODE REVIEW

**Comment by bast** [comment]
Removed code is debugged code. Excellent.

**Comment by heikef** [comment]
I just hope we do not regret it at one point but for the moment it is not needed. Thanks for the merge.

**Comment by bast** [comment]
We have the Git history. Nothing gets lost forever.

**Comment by heikef** [comment]
Sure, but we need to remember where to search and what to search.

**Comment by bast** [comment]
That's why we need good commit messages.

**Comment by heikef** [comment]
Indeed. -))

**Pull request merged**
