### PR TITLE
Scripts clean (fixes #137)

### LINKED ISSUE #137: improvements for interactive scripts
@mariavd Thank you for sharing your scripts! As promised I continue testing. There are two smaller things that you might want to change at one point. 

1. revcurrent was not working for me until I used:
`alias` revcurrent="mv current_profile.dat current_profile.dat.1 && awk '{printf \"%.6f\t%.6f\t%.6f\t%.6f\n\", \$1, -\$2, -\$4, -\$3}' current_profile.dat.1 > current_profile.dat"``

2. it would be useful to have a default at the end for the time
`Do` you accept duration= ?
Press [n] to change
n``

3. The automatic visualization of the plane does not work for me on the cluster for some reason. 
However, this is minor and probably related to our cluster.

### PR DESCRIPTION
**Pull request by mariavd**
Here is the long awaited update to the scripts. 

In addition to bug fixes, there is now a script to restart the job on a cluster and the new possibility to split the integration plane into squares.

### CODE REVIEW

**Comment by bast** [comment]
Thanks but we will need to clean up the history.

**Comment by mariavd** [comment]
Alright, I will do some rebasing.

**Comment by heikef** [comment]
It is difficult to review something here. Thanks for cleaning the history. I can contribute with testing later on.

**Comment by mariavd** [comment]
@bast  I suspect that the branch merging is causing the issue that the squash cannot be applied. Is there a way to rebase the merges, too?

**Comment by bast** [comment]
First thing I would do is to backup the branch, then rebase the branch on top of master. Then the merge commits will disappear. Then do an interactive rebase and combine those commits that should be combined.

**Comment by mariavd** [comment]
@bast  Sorry, just to make sure that I don't mess the history, by "rebase the branch on top of master", do you mean that I should merge the scripts branch with master on my fork?

**Comment by bast** [comment]
First back it up. Then run a "rebase origin/master".

**Comment by mariavd** [comment]
Did I mess something up now that I see two commits which are not mine?

**Comment by bast** [comment]
This is because you committed to your master:
https://github.com/qmcurrents/gimic/compare/master...mariavd:master

So your master will diverge and your PRs will bring in commits you did not make.

First make sure that all commits that are on your master but not on central master get on a branch, then clean up your master, then rebase this branch again.

**Comment by bast** [comment]
Do you need help with this?

**Comment by mariavd** [comment]
@bast  Actually yes. I was not sure what to do and started procrastinating. 

So I didn't understand how a commit ended up on ``master``. What is the correct way to restore my master branch?

**Comment by heikef** [comment]
Did you also update your master? We closed some issues during the last days.

**Comment by mariavd** [comment]
I just tried ``git pull upstream master``, where upstream is the main git. I can see your new commits but also the ones that I accidentially merged, which is expected.

**Comment by bast** [comment]
First question before restoring the master branch: the commits that are there, are they also part of some other branch? In other words if we delete everything you have done on master, is this a problem?

**Comment by mariavd** [comment]
I can see the same commits both on ``master`` and ``scripts-clean``.:

Master:

b6cda05 Merge branch 'master' of github.com:qmcurrents/gimic
03bd52d Merge pull request #153 from heikef/feature-no-zero
0b25666 added a check for zero entries in basis information into turbo2gimic.py and included the QCTools directory into build/bin closes #122 and partly solves issue #74
f722d07 Merge pull request #152 from heikef/feature-txt-files
60468b5 adapted tests and added one new test closes #151
1254312 do not print txt format vector fields by default
2c6a06d Merge pull request #150 from heikef/feature-clean-up-div
874ee2f removed divergence module - closes #117
988abfc Merge pull request #149 from heikef/feature-docu
3053dab included information about open-shell output into documentation closes #148
6e62e75 Merge pull request #147 from heikef/feature-repare-open-shell-vis
256456b converted all txt files to vti format
e468aa1 reintroduced open shell visualization but instead of cube with vti file format
9caba6c Merge pull request #145 from bast/radovan/reactivate-mpi
cb7de67 make it possible to launch using GIMIC_LAUNCHER env var
600bfe5 rm mpi ierr print, if there is an error, code dies earlier
29ff492 rm dead code
6cb69cb Merge pull request #144 from bast/radovan/rm-warning
de80085 get rid of compile-time warning
e1538eb Merge pull request #140 from heikef/feature-remove-edens-module
1f392bb removed edens module - closes #118
2d162be Merge pull request #139 from heikef/feature-clean-cube
1e412e9 removed cube support and acid.txt - modified edens_field.f90 file closes #138
8d091ec Merge branch 'master' of github.com:qmcurrents/gimic
1aae5fe Removed the old gradient
98f040e Merge branch 'essential-preliminary' of github.com:mariavd/gimic into essential-preliminary
a11c35b Gradient script
d83ce05 Gradient script
1ef3ce6 Introduced j_prime and j_second -> currents induced along the integration plane horizontally and perpendicularly to the integration plane horizontally
e037a42 Merge pull request #136 from mariavd/scripts-clean
fdfc768 The gradient is calculated by one script only - the others call it
765253a The build files for the scripts are in src/
5c553cc Introduced MF=X
e7fb39a bugs: centroid, anprofile; Updated the file with aliases; updated some messages to the user; introduced valueDimInp function; setup checks for the path to gimic
a8c8418 A current profile script for splitting the integration planes in squares
01d9b3a Merge pull request #134 from mariavd/scripts-clean
896ac80 Small improvements based on user feedback
db63fbf Removed old files
8d745d4 Merge pull request #131 from mariavd/scripts-clean

And scripts:

a44776b Updates to the squares script
a56f206 Scripts: Current profiles can now be restarted
2342ab9 Bugfix setup.sh
5065d1b Entering a suffix to the calculation directory possible
4155a3e A current profile script for splitting the integration planes in squares
feecf23 The gradient is calculated by one script only - the others call it
a18205d The build files for the scripts are in src/
e2b8b5a Introduced MF=X
db6e1e9 bugs: centroid, anprofile; Updated the file with aliases; updated some messages to the user; introduced valueDimInp function; setup checks for the path to gimic
adb2273 A current profile script for splitting the integration planes in squares
cdeeb8d Small improvements based on user feedback
bac8e5d Removed old files
d198b81 Introducing interactive bash scripts for setting up GIMIC jobs
95d420d rm trailing whitespace to get more meaningful diffs when comparing branches
0f04f49 Removed the old gradient
bcb2e99 Gradient script
e9d80a4 Gradient script
056d3d4 Introduced j_prime and j_second -> currents induced along the integration plane horizontally and perpendicularly to the integration plane horizontally
e197b25 added formula for GIMIC and ACID into documentation closes #126
02ebded Bash job script documentation
0873fa2 Merge pull request #124 from mariavd/docs

**Comment by bast** [comment]
OK but I really need to know: if we remove your master branch, is this a problem? Are there commits on the master branch that 1) are not on another branch and 2) that you don't want to lose?

**Comment by mariavd** [comment]
I never intentionally commit on my ``master``, so I think it will be safe to remove it.

**Comment by mariavd** [comment]
The problem happened when I misunderstood your suggestion for ``rebase origin/master``.

**Comment by heikef** [comment]
Make sure you have a copy of your scripts. Just in case.

**Comment by mariavd** [comment]
I keep them up to date both locally and on Taito, so at worst they should be recoverable.

**Comment by bast** [comment]
Good. Run these steps to restore your master branch on the fork (**all commits that are not in the central master will be lost**):
```
git clone git@github.com:mariavd/gimic.git
cd gimic
git remote add upstream git@github.com:qmcurrents/gimic.git
git fetch upstream

# find the point where upstream/master and origin/master started to diverge
# it will yield e037a42620c4a2bdc0d83b527eed041ebaec3a01
git merge-base upstream/master origin/master

# remove all commits after e037a42620
git reset --hard e037a42620c4a2bdc0d83b527eed041ebaec3a01

git pull upstream master
git push origin master

# once the command below shows no diff, you are done
git diff origin/master upstream/master
```

Once this is done, please let me know and we continue from there.

**Comment by mariavd** [comment]
Done

**Comment by bast** [comment]
Now:
1) backup the scripts-clean branch (by creating a new branch pointing to it).
2) rebase scripts-clean on top of master (`git checkout scripts-clean; git rebase master`).
3) push rebased branch to your fork and then we see how it looks.

**Comment by mariavd** [comment]
Should I force push ``scripts-clean``?

**Comment by heikef** [comment]
If you can not push otherwise I would say yes. I always use it after a rebase.

**Comment by bast** [comment]
In this case you have to force push since rebase is a history-changing operation.

**Comment by mariavd** [comment]
At least no conflicts appear now in the pull request. I will run a calculation just to be completely sure that everything works. i will let you know later how it went.

**Comment by bast** [comment]
You can also see that my commit is gone (good) and many merge commits are gone (good). Some are still left and it could be cleaned up further with an interactive rebase but I am already quite happy with the changes.

**Comment by bast** [comment]
Lesson learned: never do anything on the master branch except updating your master branch on the fork.

**Comment by mariavd** [comment]
Yes, indeed. My mistake was that I somehow ended up doing the rebase from ``master`` rather than ``git rebase master`` called from the scripts branch. Thank you for the help!

**Comment by bast** [comment]
I am handing over to Heike who will review this change.

**Comment by heikef** [comment]
Ok, let me know how your backup tests went. After all we want to be sure that the scripts are working. There are also some merge commit messages left and I am not sure if they are really needed, but after all rebase and cleaning I do not want to be so picky.

**Comment by mariavd** [comment]
Sure, Taito is completely full since yesterday and the job hasn't started yet. I managed to find some small things to fix, so there will be at least one more commit to come. I will try rebasing (properly this time).

**Comment by heikef** [comment]
Thanks Maria!

**Pull request merged**
