### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by bast**
- Update/add links
- Wrapping a long line

### CODE REVIEW

**Comment by heikef** [comment]
Good idea to add the links!

**Comment by heikef** [comment]
Again the valgrind tests failed. I thought they were removed from the TravisCI testing. The edited files should not affect the tests at all. What went wrong?

**Comment by bast** [comment]
I don't know why they fail. For sure this change is unrelated.

**Comment by heikef** [comment]
I can merge but would prefer if all tests would run through. Is the Valgrind TravisCI test really needed?

**Comment by bast** [comment]
I agree - we should not merge this. We should fix the Valgrind problem first and then rebase this PR on top of it.

**Comment by heikef** [comment]
OK.

**Comment by lnw** [comment]
Give me access to a machine where valgrind fails, and I'll fix it.  Locally they work for me ...

**Comment by bast** [comment]
I cannot reproduce it locally either. I will now rebase this branch.

**Comment by bast** [comment]
Now Travis is happy (?).

**Comment by lnw** [comment]
Interesting, now it works.  I don't think I fixed it, what I did should only have been a speed improvement.

**Comment by bast** [comment]
There is a Heisenbug somewhere.

**Comment by lnw** [comment]
Merge while it's not looking ...

**Pull request merged**
