### PR TITLE
Large refactor under the CMake hood

### PR DESCRIPTION
**Pull request by bast**
Slight changes in the setup script but changes should largely be transparent.

### CODE REVIEW

**Comment by heikef** [comment]
Thanks! A lot of cleaning up work has been done. 
Why is the renaming of some files needed? 
It is a good idea to remove what is not needed, but we will need later on automatic BLAS library or LAPACK detection.

**Comment by bast** [comment]
Renaming was to simplify for my own taste - perhaps not really needed. Currently we do not use any BLAS or LAPACK that's why I nuked that code.

**Comment by bast** [comment]
The motivation for all this work was to switch to http://autocmake.readthedocs.io - this should give us a more portable and more maintainable CMake structure.

**Comment by heikef** [comment]
Do we have to rename now all *.f90 files?

**Comment by heikef** [comment]
In any case it is just a small change from *.f90 to *.F90, no problems expected.

**Comment by bast** [comment]
Aha - the renames to F90 were needed because these files use preprocessing and there the standard is to use uppercase suffix. For files which are not preprocessed, standard is lowercase f90.

**Comment by heikef** [comment]
Ok that means we can have both.

**Comment by bast** [comment]
Yes. We need to have both.

**Pull request merged**
