### PR TITLE
The C4H4 molecule test is added and the gimic-test script modified.

### PR DESCRIPTION
**Pull request by mariavd**
The gimic-test.sh script is changed to execute test calculations on C6H6 and C4H4 and returns 0 on success. For more details check gimic-test-README.

### CODE REVIEW

**Comment by mariavd** [comment]
I made the pull request from github.com. Is that fine for now?

**Comment by bast** [comment]
Another commit got added to the PR - was this the plan? To avoid this in future I recommend to create PRs from feature branches and not from master.

**Comment by mariavd** [comment]
@bast If it was a few moments ago, then I meant to push to my fork to show it to Heike. I will now make a branch for the visualizations part.

**Comment by bast** [comment]
The one commit that came later (see just further up this thread) -  is it supposed to be integrated together with this PR? If not, then please close this one and reopen a new one from a feature branch that you can create from the last commit that was part of this PR. Sorry for extra work but it is good Git practice.

**Comment by mariavd** [comment]
The five commits from 21 hours ago should go to the PR. The one from today should not. Let's see if I do it correctly now.

**Comment by mariavd** [comment]
@bast I reverted the commit from this morning. Should I do so for the commits regarding the test molecule and the script from yesterday that are part of this pull request?

**Comment by bast** [comment]
Create a feature branch which only contains the commits that you want to submit. Then submit the PR from that feature branch. After that you can but don't have to delete the commits from your master branch.

**Comment by mariavd** [comment]
I could not manage to make the branch properly. On my fork you can see the changes but they seem to be on my master branch, not on the test-script branch. I could not get them moved. I'm sorry for the stupid questions.

**Comment by bast** [comment]
Looks fine to me. Now submit a new PR from the visualizations branch.

**Comment by mariavd** [comment]
Actually, I would like to submit the new test-script.sh on the test branch. It should look like this: https://github.com/mariavd/gimic/blob/master/test/gimic-test.sh The visualizations branch should wait until I finish some more things.

**Comment by bast** [comment]
This is how it looks now: https://github.com/qmcurrents/gimic/network
It is not clear to me how you want it to look and from which branch you want to submit the PR.

**Pull request closed without merging**
