### PR TITLE
Valgrid tests are optional

### PR DESCRIPTION
**Pull request by bast**
On Travis CI they are run but by default they are off.

### CODE REVIEW

**Comment by heikef** [comment]
Great! Thank you. Is it picky to suggest to squash everything into one commit?

**Comment by bast** [comment]
I think in this case the commits do different things so I think it is better not to squash them in this case. Only the last commit is really about the Valgrind, the rest is cleanup.

**Comment by heikef** [comment]
Do you really think that commits like "rm unused code" and "rm more unused code" are needed?

**Comment by bast** [comment]
For sure they are unrelated with the Valgrind commit. But it is totally OK for me if you prefer to squash them, then go ahead.

**Comment by heikef** [comment]
I am not able to do this online. I could accept the pull request from you and then squash the commits and then push again but without requesting code review. Would this be acceptable?

**Comment by bast** [comment]
Why can't you do this online? (in the "merge pull request" you have the choices)

But still I would here recommend to not squash, but merge as they are.

**Comment by heikef** [comment]
Ah, this is too tempting...

**Comment by heikef** [comment]
I was not aware that this option exists.... what a feeling! :) It is much easier to do this online as a reviewer....

**Pull request merged**
