### PR TITLE
Get rid of many issues warned at by the compiler

### LINKED ISSUE #165: Segmentation fault with ifort
Last week I noticed that if I compile gimic with ifort current density calculations crash with a seg fault but bond integration works fine. So, I compiled with traceback to find out what's going on, since with gcc the calculations finish. 

```
./setup --fc=ifort --extra-fc-flags='-traceback -check all' --cc=icc --cxx=icc
```

I noticed two things. 

1) The ``rank`` variable in the file below is not initialized but used in a subroutine. Probably it needs to be defined as intent in. 

```
forrtl: severe (194): Run-Time Check Failure. The variable 'initialize$RANK$_114' is being used in '/homeappl/home/mariavd/appl_taito/gimic/src/fgimic/gimic.F90(96,13)' without being defined
Image              PC                Routine            Line        Source
gimic.bin          00000000004063E8  gimic_IP_initiali          96  gimic.F90
gimic.bin          000000000040460A  MAIN__                     44  gimic.F90
gimic.bin          000000000040455E  Unknown               Unknown  Unknown
libc-2.12.so       0000000005C4ED1D  __libc_start_main     Unknown  Unknown
gimic.bin          00000000004043E9  Unknown               Unknown  Unknown
```

2) In the jvector_plots subroutine the pointer to the tensor jtens is used but not allocated. The function get_acid(r, tens) takes the pointer to the tensor as intent(in), so it receives an undefined pointer. This problematic subroutine is called by the run_cdens subroutine. I actually don't know how the code can work when compiled with gcc with this issue. 

```
forrtl: severe (408): fort: (7): Attempt to use pointer JTENS when it is not associated with a target

Image              PC                Routine            Line        Source
gimic.bin          00000000004BDB60  Unknown               Unknown  Unknown
gimic.bin          000000000045466B  jfield_class_mp_j         326  jfield.f90
gimic.bin          0000000000405689  gimic_IP_run_cden         203  gimic.F90
gimic.bin          0000000000405B5E  gimic_IP_driver_          178  gimic.F90
gimic.bin          000000000040460F  MAIN__                     45  gimic.F90
gimic.bin          000000000040455E  Unknown               Unknown  Unknown
libc-2.12.so       00007FC3D9DC2D1D  __libc_start_main     Unknown  Unknown
gimic.bin          00000000004043E9  Unknown               Unknown  Unknown
```

### PR DESCRIPTION
**Pull request by bast**
Fixes #165.

### CODE REVIEW

**Comment by bast** [comment]
Maybe @mariavd can look over this.

**Comment by mariavd** [comment]
@bast  It seems to cover many of the problems. 

I tested with ifort and it found that in ``src/fgimic/gimic.F90`` in line 90 the variable rank is printed without being initialized. Maybe it should be mpi_rank?

**Comment by bast** [comment]
Yes, should be mpi_rank, I will append to this PR.

**Comment by mariavd** [comment]
It also reports this but I don't understand what's wrong there. But the calculations complete fine. Some tests are still running locally, and then I will check with Valgrind, too.

```
forrtl: warning (406): fort: (1): In call to I/O Read routine, an array temporary was created for argument #1

Image              PC                Routine            Line        Source
gimic.bin          00000000004AAEA6  Unknown               Unknown  Unknown
gimic.bin          000000000041C6B6  getkw_class_mp_re        1674  getkw.f90
gimic.bin          000000000041AD8B  getkw_class_mp_re        1626  getkw.f90
gimic.bin          0000000000419A5D  getkw_class_mp_re        1549  getkw.f90
gimic.bin          000000000040841D  getkw_class_mp_ne         346  getkw.f90
gimic.bin          0000000000403F94  MAIN__                     38  gimic.F90
gimic.bin          0000000000403F1E  Unknown               Unknown  Unknown
libc.so.6          00007FE95454BD1D  Unknown               Unknown  Unknown
gimic.bin          0000000000403DA9  Unknown               Unknown  Unknown
```

**Comment by bast** [comment]
I don't know either - I am tempted to ignore that one for a moment. Ready to merge?

**Comment by mariavd** [comment]
I agree that it can be ignored. Running test 20/21 at the moment.

**Comment by mariavd** [comment]
No issues so far apart from the test benzene/vectors fails due to some small differences in some values in the jvec file. Maybe the reference file is old. Valgrind is now running.

**Comment by mariavd** [comment]
Valgrind reports this but I don't understand why.

```
==21278== Conditional jump or move depends on uninitialised value(s)
==21278==    at 0x41D314: __jfield_class_MOD_jvector_plots (jfield.f90:287)
==21278==    by 0x40224C: run_cdens.2443 (gimic.F90:199)
==21278==    by 0x4024F1: driver.2448 (gimic.F90:174)
==21278==    by 0x401C36: MAIN__ (gimic.F90:45)
==21278==    by 0x402D10: main (gimic.F90:8)
==21278==  Uninitialised value was created by a stack allocation
==21278==    at 0x401BFF: MAIN__ (gimic.F90:38)
```

**Comment by mariavd** [comment]
Oh, there are no spaces between the variable and .gt.

**Comment by mariavd** [comment]
Actually, this radius variable is only set when using a bond grid, which explains why there was no error reported from Valgrind for the test on bond integration but reported for the 2D current density calculation. Maybe in the if statement in jtensor.f90 one can first check if bond grid is defined and if true, compare the value of the radius.

**Comment by bast** [comment]
Should we merge this and create new issues for remaining issues?

**Comment by mariavd** [comment]
I agree.

**Comment by mariavd** [comment]
Well, maybe you can consider my comment above. It should sort out the Valgrind warning.

**Comment by bast** [comment]
Can I suggest that you add this to your Valgrind PR? But if not, then I can send a separate PR.

**Comment by mariavd** [comment]
Yes, sure.

**Comment by heikef** [comment]
A principle note for the future. If I have been assigned to review something I think there is a good reason that I take some time to review. I dislike being replaced.

**Comment by bast** [comment]
Sorry you were not replaced. I first added you as reviewer, then thought that Maria should review it since she started it, then forgot to un-assign you. That's all.

**Comment by heikef** [comment]
Ok, thanks. I dislike then being un-assigned. Resolved.

**Comment by bast** [comment]
Fine. It shall not happen again and I will be very careful in future.

**Pull request merged**
