### PR TITLE
remove in/out/up/down from documentation because it is not implemente…

### PR DESCRIPTION
**Pull request by lnw**
…d; remove test/bond-integration because it is redundant; activate lobatto grid type; add test for lobatto grid type; rename test/integration to test/integration-gauss

### CODE REVIEW

**Comment by heikef** [comment]
Thank you Lukas! Could you pleas add to your pull request that this closes issue #201 ?

**Comment by lnw** [comment]
in the comment it says 'deals with #201' ...

**Comment by heikef** [comment]
Good. Will this also close the issue?

**Comment by lnw** [comment]
It solves the two main points of #201, and raises some other questions that I expanded on in an email

**Comment by heikef** [comment]
Ok.

**Comment by heikef** [comment]
I closed #202 -Depending on the outcome of the group discussion we should open a new issue

**Pull request merged**
