### PR TITLE
bug fix in jfield.f90

### PR DESCRIPTION
**Pull request by heikef**
The bug turned up when changing from intel compiler to gfortran.

### CODE REVIEW

**Comment by bast** [comment]
This PR contains a merge commit. But I will try the auto-squashing feature of GitHub.

**Comment by bast** [comment]
Also in future please do not submit PRs from the master branch.

**Comment by bast** [comment]
For reference see what happened to PR of @mariavd

**Comment by heikef** [comment]
Sorry, I thought I was on my fork.

**Comment by bast** [comment]
You were on your fork but on the master branch of your fork.

**Comment by heikef** [comment]
so I have to for and create another branch and from this branch I fill the pull request?

**Comment by bast** [comment]
Yes. One branch for one thing only. Always file PRs from feature branches.

**Comment by heikef** [comment]
OK

**Comment by mariavd** [comment]
I think I did something wrong when trying to get the fix. I did the following:
`git checkout master`
`git pull git@github.com:qmcurrents/gimic.git`

And I can see that the file jfield.f90 has a new time stamp. Then I deleted the build folder, created it again, then 
`cmake ..` 
`make`
`make install`

I still get zeroes in jvec.vti but I suspect that it's my fault, not a bug this time.

**Pull request merged**
