### PR TITLE
Feature open shell

### PR DESCRIPTION
**Pull request by heikef**
Added an open-shell example. This needs to be checked though by the community. Closing #61

### CODE REVIEW

**Comment by bast** [comment]
Does it mean we are not sure about the correctness? If yes, I would mark it there to avoid possibly confusion on our side where we accept a value as given. I will also squash the merge commit away but this can be done on GitHub side.

**Comment by heikef** [comment]
I think the value is correct. Tested it also on HF level but I never got a reference value from Vincent for this problem nor any other test case for closed and open-shell applications. So I had to set up things on my own. There was a lot of confusion and back and forth emailing with several users regarding open-shell calculations. Therefore, I decided to share on github what we have figured out so far and let it be tested by the user community. That will most likely converge to something reasonable and usable. 
 
Alternatively one would need to recompute published values for fluorinated benzene for example including ECP's. However, I think it is not my job to figure on how things work in Gaussian and to redo others work when those being involved in the publication could easily have a look at our github and contribute.

**Comment by bast** [comment]
OK thanks for explanation. Merging.

**Comment by heikef** [comment]
I know it is not optimal but I think it is better to share what we have.

**Comment by bast** [comment]
I agree.

**Pull request merged**
