### PR TITLE
included g092gimic and lsdalton2gimic scripts

### PR DESCRIPTION
**Pull request by heikef**
@bast could you please check - thank you

### CODE REVIEW

**Comment by bast** [comment]
I guess at this point I am expected to just accept the changes, right? Or do you want feedback on the coding? Because my feedback for the future would be to not use classes/objects but build the code from functions and immutable data structures. But it might be now too late for that kind of feedback.

**Comment by heikef** [comment]
yes

**Comment by bast** [comment]
In this case I click "merge".

**Comment by heikef** [comment]
I guess this is ok.

**Pull request merged**
