### PR TITLE
vtu etc: more features, fewer bugs

### PR DESCRIPTION
**Pull request by lnw**

### CODE REVIEW

**Comment by bast** [comment]
Thanks!

**Comment by heikef** [comment]
Which features? Why is there no description provided?

**Comment by lnw** [comment]
Did I sneak a bugfix past you ? :)

**Comment by heikef** [comment]
@lnw next time it would not be wrong to a) assign a reviewer b) provide a description.

**Comment by bast** [comment]
I think the "blame" should go to me. To me this looked good, I merged, responsibility is on me.

**Comment by bast** [comment]
One possible problem with assigning a reviewer is that the reviewer may not have time and other may then think: "aha, this is not for me so I can ignore it" and the submitter waits.

**Comment by lnw** [comment]
Assigning a reviewer ... I don't mind either way.

As for "No description provided", that's not an accident.  I do my very best to write readable code, have a look, you will probably find  that it's quite obvious what I did.  I write moderately helpful commit messages.   And I entirely refuse to spend time writing "descriptions", because they are not part of git, but are confined to the github ecosystem.  They cannot be seen by anyone who checks out code and tries to understand something, and I don't think it's anyone's workflow to refer to the pull request description on github while reading code.

**Comment by heikef** [comment]
@bast there is nobody to blame 
@lnw a description helps to grab quickly what this pull request is all about. A commit message like "fewer bugs" is not informative at all.

**Pull request merged**
