### PR TITLE
compile and test on two cores

### PR DESCRIPTION
**Pull request by bast**
Probably/hopefully speeds things up a bit.

### CODE REVIEW

**Comment by bast** [comment]
It speeds up things a bit but also is IMO a good test that we got dependencies right when compiling on multiple cores.

**Comment by heikef** [comment]
Is this really needed? Normally I am using something like make -j20 when compiling. Do we really need to add the -j2 option into the script? It is not a big thing, I am just curious.

**Comment by bast** [comment]
It's faster and we might detect bad CMake code that may happily work on one core.

**Comment by bast** [comment]
But it's not really really needed :-) We can live happily without if there is a good reason to not have this.

**Comment by heikef** [comment]
Ok, ok, we do everything to improve the code. Agreed.

**Pull request merged**
