### PR TITLE
check if some files even exist, before reading.  …

### PR DESCRIPTION
**Pull request by lnw**
Reduces the number of confused users.

### CODE REVIEW

**Comment by bast** [comment]
Change looks good. Just to confirm: in this case it makes sense to not stop the calculation if these files do not exist?

**Comment by lnw** [comment]
For a missing ele it definitely makes sense to not abort.  In case of the other three, it would as far as I can see be adequate to abort.  Runtime wise it doesn't matter, because not much else happens.  If we ever get the option to do several tasks in a single job file, it would make sense to bail out selectively.
So, I slightly tend to leave everything as it is, but I can also abort.

**Comment by bast** [comment]
These are generated files? If yes, how can they not exist?

I wonder whether according to the principle of minimum surprise it would not be more careful to stop with a nice error message. I am always worried about producing strange numbers. Crash is better than wrong numbers IMO.

**Comment by lnw** [comment]
The files are generated with a) a script in tools and b) a third party prog.  It is the user's responsibility to create them and a user could fail to do so.

This is exactly why I'm printing a message saying that files are missing and therefore nothing will be done. Previously there were wrong (=0) results.

**Comment by bast** [comment]
OK - thanks for explanation!

**Comment by lnw** [comment]
Tak skal du ha!

**Pull request merged**
