### PR TITLE
Feature ubuntu test

### PR DESCRIPTION
**Pull request by heikef**
fixed a bug in jfield.f90 that appeared under ubuntu 16.10 virtual box - review @bast  

the rebase stuff was not working for me - I created a new branch and updated before the master on my fork

### CODE REVIEW

**Comment by bast** [comment]
I cannot accept this one and I want to explain you why: One of your commits is "bug fix in jfield.f90" - this commit already is on the central repo: https://github.com/qmcurrents/gimic/commit/6b1deaaa24205ecaa9fa9f3dec5ce5032d281e5d - If I merge it, it will be there twice. Please review your pull request before you submit it.
What exactly did not work for you?

**Comment by heikef** [comment]
I understand your concern. I got the feature branch from my fork, then I changed and commited. The commit message is  "fixed a bug in jfield.f90 under ubuntu 16.10 virtual box" - I did this explicitly to avoid same commit messages. At the moment I do not see what went wrong. Perhaps I should make a completely new fork and a new feature-branch - modify - commit - push - and send a new pull request? 

Concerning the rebase, I tired 
git rebase -i HEAD~5 - then I edited in the editor what is pick and what is squash - but all the " 	Merge branch 'master' of github.com:qmcurrents/gimic" stuff did not appear there at all. At the end
git log told me that all went wrong 

I got this from this page: 
http://stackoverflow.com/questions/495345/how-to-remove-selected-commit-log-entries-from-a-git-repository-while-keeping-th

**Comment by bast** [comment]
Can this one be closed? I guess it is already in.

**Comment by heikef** [comment]
yes we can close it

**Pull request closed without merging**
