### PR TITLE
Apptainer container support

### PR DESCRIPTION
**Pull request by tjjarvinen**
This will add definition file to build [Apptainer](https://apptainer.org/) container, and a README.md file to give instructions on building and using the container.

The main point with this is to have easy access to Gimic. Basicly you only need to install Apptainer, after which you can build the container and have access to Gimic without the need to install any dependencies. Also, moving Gimic binary (container) to other computers becames trivial with the container framework.
 The choise of Apptainer (former Singularity) was taken because it is developed with HPC in mind and many supercomputers (like the ones in Finland) use it.

The problem with the container is that some of the scripts in `jobscripts` folder call external programs. These wont work with the container. Because by definition container does not depend on external programs. This mainly affects scripts with "cluster" in their name, as they call Slurm. The versions with "local" in their names should work.

For visualization scripts, I added gnuplot into the container. This does however increase the size of the container by an extra 100MB to about 370MB total.

@mariavd promised to edit the scripts, so that they work with the container.
 In my opinnion, the way to go, is to remove all Slurm commands from the scripts and have the scripts output Slurm batch file, which the user can submit outside the container. That being said there is a lot of room to improve the scripts in general...

But other than that, the Gimic container should be fully working.

### CODE REVIEW

**Comment by heikef** [comment]
Dear Teemu @tjjarvinen, thank you for this initiative! I think the benefits are clear. May you please comment on why you did not go for a docker solution? I am asking this just out of curiosity. 
From my point of view it would be important that a) all test we have so far are running through and b) that this new approach is tested by several people. 
I am assigning @bast to review your changes since he knows best about HPC and containerization. Hope this is ok with you, Radovan @bast since it implies extra work.

**Comment by heikef** [comment]
Nice! I see all tests passed through! No objections from my side to merge. Regarding the bash scripts we got feedback that users find them very helpful. Sooner or later we should get a python version of them. @mariavd  will for sure disapprove. ;) Regarding gnuplot, it is only helpful when you need checking the integrations planes by hand (eg. when neighboring currents are present) otherwise the integration scans are very reliable.

**Comment by bast** [comment]
Thanks a lot! As to Apptainer vs Docker: Apptainer is more suitable for multi-user clusters (although one can convert Docker images) so I support that choice. I did not yet look at the changes but will do so ASAP.

**Review by bast — APPROVED** [review]
This looks great for me. Thanks so much for this contribution!

**Comment by bast** [comment]
Oops sorry for a late question. Why is the density.txt removed as part of this PR?

**Comment by tjjarvinen** [comment]
> Oops sorry for a late question. Why is the density.txt removed as part of this PR?

`desity.txt` is a symbolic link to a file that does not exist, which causes an error when Apptainer moves files to build the container.  So, to make container building work the broken symbolic link needed to be removed.

> May you please comment on why you did not go for a docker solution?

The main issue with Docker is that it runs containers in root space. Meaning that you need to have root access in order to run containers. Apptainer on the other hand runs containers in user space, which makes it much more usable in HPC environment.

**Comment by bast** [comment]
Thank you for the explanation!

**Pull request merged**
