### PR TITLE
Ubuntu test

### PR DESCRIPTION
**Pull request by heikef**
tested on ubuntu 16.10 system via virtual box and fixed a bug @bast please review

### CODE REVIEW

**Comment by bast** [comment]
Please look at the commits of this PR - it does not look right. Looks like you haven't updated your local branch after I squashed your commits upstream.

**Comment by heikef** [comment]
indeed - now it should be ok

**Comment by bast** [comment]
This PR contains 5 commits: https://github.com/qmcurrents/gimic/pull/13/commits - is this the plan?

**Comment by heikef** [comment]
No - it would be nice to remove the Merge branch "master" of github stuff but how do I do this?

**Comment by bast** [comment]
Rebase and squash. Exercise this on a temporary branch so that you can roll back.

**Comment by heikef** [comment]
by the way this page might be helpful albeit it did not work for me

http://stackoverflow.com/questions/495345/how-to-remove-selected-commit-log-entries-from-a-git-repository-while-keeping-th

**Pull request closed without merging**
