### PR TITLE
new try add bug fix ubuntu 16.10 virtualbox

### PR DESCRIPTION
**Pull request by heikef**
It is only one line changed in jfield.f90 therefore I did a complete new start.

### CODE REVIEW

**Comment by heikef** [comment]
should have added @bast

**Comment by bast** [comment]
You don't need to add @bast if you add me as reviewer (top right).

**Comment by bast** [comment]
My only complaint here is the commit message "new try" is completely out of context for everybody except us three who remember the struggle of the PRs :-) But feel free to merge.

**Comment by heikef** [comment]
ok ok -)) before doing the whole thing again I decided to merge - next time the commit message will fit better

**Pull request merged**
