### PR TITLE
added citation information into README.md closes #235

### LINKED ISSUE #235: add a citation section into README
I think adding the standard citations for using gimic would be helpful for new users. This should be done on the main / front page of our project.

### PR DESCRIPTION
**Pull request by heikef**
Added some relevant citations regarding the usage of GIMIC. Included also the G09 interface by Vincent because a lot of applications would not have been possible without it.

### CODE REVIEW

**Comment by heikef** [comment]
For some reason the Valgrind test failed. I touched only the README.md file. It is unclear to me why we run into this problem.

**Comment by heikef** [comment]
Would it be ok to merge anyway? The problem is for sure not the README.md file

**Comment by bast** [comment]
The test is brittle. We need to fix the Valgrind test (#245). It is OK for me if we fix this later.

**Review by bast — APPROVED** [review]

**Comment by heikef** [comment]
Ok, thank you. Then I will merge.

**Pull request merged**
