### PR TITLE
Fix Travis.

### PR DESCRIPTION
**Pull request by guacke**
We seem to have broken your Travis CI build. We will try to fix this in the following commits.

### CODE REVIEW

**Comment by bast** [comment]
I am not sure it was you. There was an issue before. We need to check the log as soon as it completes. It might be an issue on our side.

**Comment by bast** [comment]
OK seems to be a different error but on the upside it looks like you have fixed #62. Let me know if you need assistance fixing it. Thanks again for your work!

**Comment by guacke** [comment]
This commit should fix the Travis CI problems caused by our previous commit.

**Comment by bast** [comment]
Thank you! I will squash the commits into one.

**Pull request merged**
