### PR TITLE
Scripts are finally here (fixes #108)

### LINKED ISSUE #108: Add new scripts for scans
This is to make usage more convenient for users. @mariavd will take care of this

### PR DESCRIPTION
**Pull request by mariavd**
So I apparently messed up something and git says that automatic merge is impossible but I can't see where is the conflict. So it seems that I have committed changes to the documentation from the wrong branch. 

I have not rebased any commits yet into this new branch called Scripts. The original one was ``jobscripts``. I intend to rebase those "bug fix" ones to their previous ones.

### CODE REVIEW

**Comment by mariavd** [comment]
Conflict resolved but I ended up with a dirty working tree and I can't rebase.

**Comment by bast** [comment]
I trust the code is fine (too many files for me to go through all of them) but we need to tidy up the history as you have said. What is the issue with Git? Do you need some help? If yes, what is the problem?

**Comment by bast** [comment]
Can you please write a super short summary of what these scripts do? Just so we know what we are merging here.

**Comment by mariavd** [comment]
@bast The scripts prepare the input files for GIMIC interactively, asking the user what parameters they want for the calculation. The current profile analysis is based on splitting the selected integration plane into thin slices and integrating each of them as a separate calculation. If using the cluster version of the script, it sends the batch job to the queue. Finally, the respective script parses the results, plots them in EPS files and gives some suggestions about what domains can be seen in the profile along the distance. The user then can select which peaks of the profile to integrate - summing up the outputs, no new GIMIC calculations. So far it has proven to be trustworthy. 

I cannot rebase the history because I messed up my ``jobscript`` branch, which I was originally working on. I accidentally ``git add``-ed a wrong file and ``git checkout -- filename`` did not remove it. Googling suggested doing ``git reset HEAD``; or maybe I tried ``git pull`` from origin first, I don't remember exactly. This branch was created already last year and it was never merged to ``master``. I ended up with seeing a huge number of untracked and tracked files in ``git status`` that have been added or removed in the past year. I thought this can be ignored and committed the last few changes to the scripts. Then, ``git rebase`` does not work and returns:

```
.......
tools/g092gimic/BasisSet.py: needs update
tools/g092gimic/Gaussian2gimic.py: needs update
tools/qchem/README: needs update
tools/turbo2gimic.py.in: needs update
Working tree is dirty
```

At some point I created a new branch from the ``jobscripts`` but it carries the same issues.

**Comment by mariavd** [comment]
If it is too difficult to fix, I can just forget about this branch, and start working on a new one from the latest versions of the scripts. The files have changed significantly since the beginning but chances are that I will not need to go back in history.

**Comment by bast** [comment]
My recommendation is: keep your original branch for archaeological purposes. Create a new branch and transfer the scripts to that branch and submit PR from there.

**Comment by mariavd** [comment]
Alright, I am closing this PR.

**Pull request closed without merging**
