### PR TITLE
Bash job script documentation

### PR DESCRIPTION
**Pull request by mariavd**
This is the documentation for the scripts. They are on the way soon.

### CODE REVIEW

**Comment by heikef** [comment]
Thank you, Maria but do not forget to add your scripts as well.

**Comment by mariavd** [comment]
@heikef  I am trying but I messed up and now automatic merging fails...

**Comment by heikef** [comment]
It was also for me a mistake to merge your stuff. I ended up in a huge mess and at the end I had to redo everything.

**Comment by mariavd** [comment]
I'm sorry, must be might fault.

**Comment by heikef** [comment]
It is not your fault. It was my mistake. No worries.

**Comment by bast** [comment]
I am not sure what happened, but work on branches and keep them separate. Never merge from one feature branch into another.

**Pull request merged**
