### PR TITLE
included qchem + fermion++ scripts 

### PR DESCRIPTION
**Pull request by heikef**
The scripts were provided by J. Kussmann - I included this into the README file @bast

### CODE REVIEW

**Comment by bast** [comment]
Thanks!

**Comment by bast** [comment]
By accepting these we assume that these sources are provided to us under our license. We should probably state it somewhere.

**Comment by heikef** [comment]
We did not talk about a license to somebody

**Comment by bast** [comment]
I am editing your reply (please do not quote my text if you reply directly through email).

**Comment by bast** [comment]
We simply cannot accept source code if it conflicts with our license terms.

**Comment by heikef** [comment]
Agreed.

**Pull request merged**
