### PR TITLE
fix estimated time

### PR DESCRIPTION
**Pull request by lnw**
1) fix wrong ETA, and make obvious why there is a factor
2) replace multiple divisions by multiplications (so it is obvious that the order of execution is irrelevant)

### CODE REVIEW

**Review by bast — APPROVED** [review]
Thank you!

**Comment by heikef** [comment]
Is this solving as well issue #170 ? Thanks for you effort, Lukas!

**Comment by lnw** [comment]
No, that is unrelated. #170 is about wrong final times in case of OMP, but this patch just fixes the estimated time that is printed at the beginning of a run.

**Comment by heikef** [comment]
Ok. Thank you.

**Pull request merged**
