### PR TITLE
Test scripts for the 2D and 3D current density calculations

### PR DESCRIPTION
**Pull request by mariavd**
There are two scripts in the test/gimic-test-2D.sh and test/gimic-test-3D.sh, which can the example for current density calculations in 2D or 3D for benzene. The vti and cube files are compared for differences.

### CODE REVIEW

**Comment by bast** [comment]
And now rebase your branch on top of master to get rid of the two merge commits.

**Comment by mariavd** [comment]
Any better now?

**Comment by bast** [comment]
Except that there is the "new try add bug fix ubuntu 16.10 virtualbox" which I think does not belong there.

**Comment by mariavd** [comment]
Maybe now it's fine?

**Comment by bast** [comment]
A lot better now. When submitting a PR please always check whether there are commits in there which you did not expect to be there.

**Pull request merged**
