### PR TITLE
more brevity

### PR DESCRIPTION
**Pull request by bast**
Trimmed the README a bit.

### CODE REVIEW

**Comment by bast** [comment]
Is the information about the two supported codes still correct in the README?

**Comment by heikef** [comment]
Thanks. The README could be extended to G09, QChem, FERMION++ and LSDalton.

**Comment by bast** [comment]
Great! Can you please add these?

**Comment by bast** [comment]
Sorry - I can actually add this to the PR - hold on.

**Comment by bast** [comment]
Now it's better - for your review.

**Comment by heikef** [comment]
Yes, it would be easier if you just add this line. Thank you.

**Pull request merged**
