### PR TITLE
fixed cfour hash issue for two character elements

### PR DESCRIPTION
**Pull request by heikef**
- included a replacement of "#" to " #" in MOL file into mk_grid.py
- problem was that two character elements have not been recognized properly  like "NI#1" now "NI #193 
- note this holds only for MOL files generated by CFOUR

### CODE REVIEW

**Comment by heikef** [comment]
@bast I changed only a script that does not influence the gimic build at all. Do you happen to have an idea why all tests are failing? 
- looks like a cmake problem: Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found version "3.10.6")

**Comment by bast** [comment]
I am looking into it ...

**Comment by bast** [comment]
That problem is now fixed. And another appeared. Something seems to leak memory. But this might now come from this PR.

**Comment by heikef** [comment]
How can this be? I changed only a script used outside of gimic. Anyway, thank you for looking into this!

**Comment by bast** [comment]
Sorry I meant to write that this probably does not come from this PR. I will merge. The memory leak problem is probably older and needs to be investigated separately.

**Pull request merged**
