### PR TITLE
More cleanup in testing

### PR DESCRIPTION
**Pull request by bast**
Another quarter million lines of text gone.

### CODE REVIEW

**Comment by heikef** [comment]
I assume the "nuclear waste" is only removed regarding the test example. The out commented keywords are important and should be kept as an option for the input. For the specific test case we look at here they are not needed indeed. - Yes, this is the case. -))

**Comment by bast** [comment]
No, outcommented code does not belong here. Keywords may and will change and then the commented code is confusing both for users (why does this not work anymore?) and developers (will this be needed in future? but nobody is using it).

For me outcommented input examples are a symptom for the following frequent problems:
- input format is not intuitive
- keywords are not intuitive
- documentation is not helpful

**Comment by heikef** [comment]
Thanks for the cleanup.

**Comment by heikef** [comment]
I think therefore we have issue  #84. 

From a user's point of view. The keywords are useful and needed. The input format is very intuitive when you understand the "gimic logic". Documentation can always be optimized. At the moment I would not call it unhelpful.  

I want to keep the keywords!

**Comment by bast** [comment]
You want to keep out-commented keywords in the tests? Why not put them in some examples? The tests should test one thing only. I find it very confusing to have them in the tests.

**Comment by heikef** [comment]
No, I do not want to keep out-commented stuff in the tests. I was pointing out that the keywords that are out-commented are still relevant and should not be in general removed from the input. This is not related to this specific test. Apparently that was not clearly stated. Sorry for this. Hope this is clear now.

**Comment by bast** [comment]
OK I was of course not planning at removing any keywords :-) Only removed out-commented lines.

**Comment by heikef** [comment]
Good. -)) Just wanted to be sure about this. One never knows.

**Pull request merged**
