### PR TITLE
Remove cmake2 / python2

### PR DESCRIPTION
**Pull request by lnw**
bump up version of cmake to 3.12+ and python to 3.0+, corresponds to #274

### CODE REVIEW

**Comment by lnw** [comment]
I left FindCython because for example my system doesn't ship that ... furthermore, I assumed that a python3-cython-binary is called 'cython3'.

**Comment by heikef** [comment]
@lnw may you append the commit message and tell that this closes issue  #274 ?

**Comment by heikef** [comment]
@lnw something went wrong, all checks failed.

**Comment by lnw** [comment]
well, as you can see I am working on that.  It's a problem with the build system which I cannot verify locally.

**Comment by heikef** [comment]
@lnw thank you for your work, perhaps @bast can help

**Comment by heikef** [comment]
It seems to work now @lnw. I see you adapted all python files. Thanks a lot for your work. I think since we did not hear something from @bast it is ok when I am doing the merge.

**Comment by lnw** [comment]
Thanks @heikef !  Let's see if anyone complains ... one can always make a second small commit.

**Comment by heikef** [comment]
@lnw I am complaining and regret the merge. It was a big mistake. On my Mac nothing compiles. It is a huge mess. I will open a new issue. For the future I learned to clone first your fork and test and then approve.

**Comment by bast** [comment]
For reference: followed up in #280.

**Pull request merged**
