### PR TITLE
Updated the docs on the gimic input file and its usage

### PR DESCRIPTION
**Pull request by mariavd**
It can be made better but at least I removed some outdated parts and tried explaining more. The input.rst is restructured. 

I noticed the grid.rst. It overlaps to a major extent with the input.rst. Ideally we should show a picture illustrating the meaning of the integration plane. I made two a long time ago but they are outdated because the labels read in/out/up/down.

### CODE REVIEW

**Comment by heikef** [comment]
Thanks for updating the documentation, but why do we have conflicts here?

**Comment by mariavd** [comment]
I don't know. When I click on *Resolve conflicts*, it never loads the file for me. Do you see anything there?

**Comment by heikef** [comment]
Same here.

**Comment by heikef** [comment]
Did you check that you do not have merge conflicts? >>>>> or <<<<< in an *.rst file?

**Comment by lnw** [comment]
I guess qmcurrents:master is ahead of mariavd:mariavd-docs-update by at least one commit.  If you go to you local branch, pull+merge from qmcurrents:master and push to mariavd:mariavd-docs-update that should fix it.

**Comment by mariavd** [comment]
@lnw was right, my branch was not synchronised to upstream master. 

I noticed more issues in those two pages but I will fix them another time.

**Comment by heikef** [comment]
ok, thank you.

**Pull request merged**
